name: tcg_index

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [tcg_index]
  schedule:
    - cron: "*/20 * * * *"

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false

jobs:
  cache-datastore:
    uses: ./.github/workflows/cache-file.yml
    with:
      url: ${{ vars.DATASTORE_MAGIC }}
      path: "datastore/"
      game: "magic"
    secrets: inherit

  deploy:
    name: ${{ github.workflow }}
    needs: [cache-datastore]
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: ${{ github.workflow }}
      game: "magic"
      datastore-filepath: ${{ needs.cache-datastore.outputs.filepath }}
      datastore-cache-key: ${{ needs.cache-datastore.outputs.key }}
    secrets: inherit
